-- Highlight ESP for all items in folder: Monsters
-- Generated by Secure Explorer

local Players = game:GetService("Players")

local espEnabled = true
local espObjects = {}

-- Target folder
local targetFolder = Workspace.Monsters

-- Highlight ESP creation function
local function createHighlightESP(target)
    if not target then return end
    
    local highlight = Instance.new("Highlight")
    highlight.Adornee = target
    highlight.FillColor = Color3.fromRGB(147, 112, 219)
    highlight.OutlineColor = Color3.fromRGB(255, 255, 255)
    highlight.FillTransparency = 0.5
    highlight.OutlineTransparency = 0
    highlight.Parent = target
    
    espObjects[target] = {highlight = highlight}
end

-- Remove ESP
local function removeESP(target)
    if espObjects[target] then
        if espObjects[target].highlight then
            espObjects[target].highlight:Destroy()
        end
        espObjects[target] = nil
    end
end

-- Function to get all items in folder
local function getAllItemsInFolder()
    local targets = {}
    
    for _, child in pairs(targetFolder:GetChildren()) do
        if child:IsA("BasePart") or child:IsA("Model") then
            table.insert(targets, child)
        end
    end
    
    return targets
end

-- Update ESP for all items
local function updateFolderESP()
    -- Clear existing ESP
    for target, esp in pairs(espObjects) do
        removeESP(target)
    end
    
    if not espEnabled then return end
    
    -- Create ESP for all items in folder
    local targets = getAllItemsInFolder()
    for _, target in pairs(targets) do
        createHighlightESP(target)
    end
end

-- Initial ESP update
updateFolderESP()

-- Monitor for new items in folder
targetFolder.ChildAdded:Connect(function()
    task.wait(0.1)
    updateFolderESP()
end)

targetFolder.ChildRemoved:Connect(function()
    task.wait(0.1)
    updateFolderESP()
end)

print("Highlight ESP loaded for folder:", targetFolder.Name)
print("ESP is currently:", espEnabled and "ON" or "OFF")
