local ReplicatedStorage: ReplicatedStorage = game:GetService("ReplicatedStorage")
local WeaponPath: ModuleScript = ReplicatedStorage:WaitForChild("Modules"):WaitForChild("WeaponSettings"):WaitForChild("Gun"):WaitForChild("Revolver"):WaitForChild("Setting"):WaitForChild("1")

local function PatchModule()
    local success: boolean, weaponTable: table = pcall(require, WeaponPath)
    
    if success and type(weaponTable) == "table" then
        weaponTable.FireRate = 0.05
        weaponTable.Auto = true
        weaponTable.ReloadTime = 0
        weaponTable.TacticalReloadTime = 0
        weaponTable.AmmoPerMag = 999
        weaponTable.Ammo = 999
        weaponTable.MaxAmmo = 999
        weaponTable.ReloadAnimationSpeed = 100
        weaponTable.VMReloadAnimationSpeed = 100
        weaponTable.VMTacticalReloadAnimationSpeed = 100
        weaponTable.EquipTime = 0
        weaponTable.SwitchTime = 0
        weaponTable.Accuracy = 0
        weaponTable.Spread = 0
        weaponTable.Recoil = 0
        weaponTable.CameraRecoilingEnabled = false
        weaponTable.DelayBeforeFiring = 0
        weaponTable.DelayAfterFiring = 0
        weaponTable.SelectiveFireEnabled = true
        weaponTable.FireRates = {0.05, 0.05, 0.05, 0.05}
    end
end

task.spawn(PatchModule)

local v1: table = {
    ["ModuleName"] = "1",
    ["Handles"] = { "Handle" },
    ["Auto"] = true,
    ["BaseDamage"] = 90,
    ["FireRate"] = 0.05,
    ["ReloadTime"] = 0,
    ["AmmoPerMag"] = 999,
    ["Spread"] = 0,
    ["DamageMultipliers"] = {
        ["Head"] = 2
    },
    ["HeadshotDamageMultiplier"] = 2,
    ["EquipTime"] = 0,
    ["EquippedAnimationID"] = 96081515108008,
    ["EquippedAnimationSpeed"] = 1,
    ["IdleAnimationID"] = 116767152044191,
    ["IdleAnimationSpeed"] = 1,
    ["ReloadAnimationID"] = nil,
    ["ReloadAnimationSpeed"] = 100,
    ["FireAnimations"] = {
        {
            ["FireAnimationID"] = 97903397192938,
            ["FireAnimationSpeed"] = 1
        }
    },
    ["VMEquippedAnimationID"] = 115052659699836,
    ["VMEquippedAnimationSpeed"] = 1,
    ["VMIdleAnimationID"] = nil,
    ["VMIdleAnimationSpeed"] = 1,
    ["VMReloadAnimationID"] = nil,
    ["VMReloadAnimationSpeed"] = 100,
    ["VMSprintAnimationID"] = nil,
    ["VMSprintAnimationSpeed"] = 1,
    ["VMFireAnimations"] = {
        {
            ["VMFireAnimationID"] = 89445782249690,
            ["VMFireAnimationSpeed"] = 1
        }
    },
    ["AimAnimationsEnabled"] = false,
    ["AimIdleAnimationID"] = nil,
    ["AimIdleAnimationSpeed"] = 1,
    ["AimFireAnimations"] = {
        {
            ["AimFireAnimationID"] = nil,
            ["AimFireAnimationSpeed"] = 1
        }
    },
    ["AltAnimationID"] = nil,
    ["AltAnimationSpeed"] = 1,
    ["AltTime"] = 1,
    ["VMAltAnimationID"] = nil,
    ["VMAltAnimationSpeed"] = 1,
    ["KeepAimingOnReloading"] = true,
    ["AlignToAimPoint"] = true,
    ["LaserTrailEnabled"] = false,
    ["LaserTrailWidth"] = 0.1,
    ["LaserTrailHeight"] = 0.1,
    ["LaserTrailColor"] = Color3.fromRGB(0, 170, 255),
    ["RandomizeLaserColorIn"] = "None",
    ["LaserColorCycleTime"] = 5,
    ["LaserTrailMaterial"] = Enum.Material.Neon,
    ["LaserTrailShape"] = "Block",
    ["LaserTrailReflectance"] = 0,
    ["LaserTrailTransparency"] = 0,
    ["LaserTrailVisibleTime"] = 1,
    ["LaserTrailFadeTime"] = 0.5,
    ["ScaleLaserTrail"] = false,
    ["LaserTrailScaleMultiplier"] = 1.5,
    ["DamageableLaserTrail"] = false,
    ["LaserTrailDamage"] = 20,
    ["LaserTrailConstantDamage"] = false,
    ["LaserTrailDamageRate"] = 0.1,
    ["LaserTrailKnockback"] = 0,
    ["LaserTrailDebuff"] = false,
    ["LaserTrailDebuffName"] = "",
    ["LaserTrailDebuffChance"] = 100,
    ["ApplyLaserTrailDebuffOnCritical"] = false,
    ["LaserTrailCriticalDamageEnabled"] = false,
    ["LaserTrailCriticalBaseChance"] = 5,
    ["LaserTrailCriticalDamageMultiplier"] = 3,
    ["LimitedAmmoEnabled"] = false,
    ["Ammo"] = 999,
    ["MaxAmmo"] = 999,
    ["CircularCrosshairEnabled"] = false,
    ["CrossSize"] = 1,
    ["CrossExpansion"] = 70,
    ["CrossSpeed"] = 25,
    ["CrossDamper"] = 1,
    ["HitmarkerEnabled"] = true,
    ["HitmarkerSoundIDs"] = { 9117969687 },
    ["HitmarkerColor"] = Color3.fromRGB(255, 255, 255),
    ["HitmarkerFadeTime"] = 0.4,
    ["HitmarkerSoundPitch"] = 1,
    ["HeadshotHitmarker"] = true,
    ["HitmarkerColorHS"] = Color3.fromRGB(255, 0, 0),
    ["HitmarkerFadeTimeHS"] = 0.4,
    ["HitmarkerSoundPitchHS"] = 1,
    ["CameraRecoilingEnabled"] = false,
    ["Recoil"] = 0,
    ["AngleX_Min"] = 0,
    ["AngleX_Max"] = 0,
    ["AngleY_Min"] = 0,
    ["AngleY_Max"] = 0,
    ["AngleZ_Min"] = 0,
    ["AngleZ_Max"] = 0,
    ["Accuracy"] = 0,
    ["RecoilSpeed"] = 15,
    ["RecoilDamper"] = 0.65,
    ["RecoilRedution"] = 0.5,
    ["ViewmodelRecoilInfluence"] = 0,
    ["TweenLength"] = 0.8,
    ["EasingStyle"] = Enum.EasingStyle.Quint,
    ["EasingDirection"] = Enum.EasingDirection.Out,
    ["TweenLengthNAD"] = 0.8,
    ["EasingStyleNAD"] = Enum.EasingStyle.Quint,
    ["EasingDirectionNAD"] = Enum.EasingDirection.Out,
    ["IronsightEnabled"] = false,
    ["FieldOfViewIS"] = 50,
    ["MouseSensitiveIS"] = 0.8,
    ["SpreadRedutionIS"] = 0.6,
    ["CrossScaleIS"] = 0,
    ["SniperEnabled"] = false,
    ["FieldOfViewS"] = 12.5,
    ["MouseSensitiveS"] = 0.2,
    ["SpreadRedutionS"] = 0.6,
    ["CrossScaleS"] = 0,
    ["ScopeSensitive"] = 0.25,
    ["ScopeDelay"] = 0,
    ["ScopeKnockbackMultiplier"] = 5,
    ["ScopeKnockbackSpeed"] = 15,
    ["ScopeKnockbackDamper"] = 0.65,
    ["ScopeSwaySpeed"] = 15,
    ["ScopeSwayDamper"] = 0.65,
    ["SmokeTrailEnabled"] = false,
    ["SmokeTrailRateIncrement"] = 1,
    ["MaximumRate"] = 4,
    ["MaximumTime"] = 1,
    ["SilenceEffect"] = false,
    ["EchoEffect"] = true,
    ["LowAmmo"] = false,
    ["RaisePitch"] = false,
    ["DistantSoundIds"] = { 177174605 },
    ["DistantSoundVolume"] = 1.5,
    ["InspectAnimationEnabled"] = true,
    ["InspectAnimationID"] = nil,
    ["InspectAnimationSpeed"] = 1,
    ["VMInspectAnimationID"] = nil,
    ["VMInspectAnimationSpeed"] = 1,
    ["TacticalReloadAnimationEnabled"] = false,
    ["TacticalReloadAnimationID"] = nil,
    ["TacticalReloadAnimationSpeed"] = 100,
    ["TacticalReloadTime"] = 0,
    ["VMTacticalReloadAnimationID"] = nil,
    ["VMTacticalReloadAnimationSpeed"] = 100,
    ["DamageDropOffEnabled"] = false,
    ["ZeroDamageDistance"] = 10000,
    ["FullDamageDistance"] = 1000,
    ["HitEffectEnabled"] = false,
    ["HitSoundIDs"] = { 151130059 },
    ["HitSoundPitchMin"] = 1,
    ["HitSoundPitchMax"] = 1.5,
    ["HitSoundVolume"] = 1,
    ["CustomHitEffect"] = false,
    ["BulletHoleEnabled"] = false,
    ["BulletHoleSize"] = 0.3,
    ["BulletHoleTexture"] = { 1987889998 },
    ["BulletHoleVisibleTime"] = 2,
    ["BulletHoleFadeTime"] = 1,
    ["PartColor"] = true,
    ["BloodEnabled"] = true,
    ["HitCharSndIDs"] = { 7837535984, 7837536401, 7837536770 },
    ["HitCharSndPitchMin"] = 1,
    ["HitCharSndPitchMax"] = 1,
    ["HitCharSndVolume"] = 1,
    ["BloodWoundEnabled"] = false,
    ["BloodWoundSize"] = 0.5,
    ["BloodWoundTexture"] = { 2078626 },
    ["BloodWoundTextureColor"] = Color3.fromRGB(255, 0, 0),
    ["BloodWoundVisibleTime"] = 3,
    ["BloodWoundFadeTime"] = 1,
    ["BloodWoundPartColor"] = true,
    ["WhizSoundEnabled"] = true,
    ["WhizSoundIDs"] = {
        3092866899,
        3809085250,
        3809085650,
        3809085996,
        3809086455
    },
    ["WhizSoundVolume"] = 1,
    ["WhizSoundPitchMin"] = 1,
    ["WhizSoundPitchMax"] = 1,
    ["WhizDistance"] = 25,
    ["MuzzleFlashEnabled"] = true,
    ["MuzzleLightEnabled"] = true,
    ["LightBrightness"] = 4,
    ["LightColor"] = Color3.new(1, 1.1098039215686275, 0),
    ["LightRange"] = 15,
    ["LightShadows"] = true,
    ["VisibleTime"] = 0.01,
    ["ShotgunEnabled"] = false,
    ["BulletPerShot"] = 8,
    ["ShotgunPump"] = false,
    ["ShotgunPumpinSpeed"] = 100,
    ["ShotgunPumpinAnimations"] = {
        {
            ["ShotgunPumpinAnimationID"] = nil,
            ["ShotgunPumpinAnimationSpeed"] = 100
        }
    },
    ["VMShotgunPumpinAnimations"] = {
        {
            ["VMShotgunPumpinAnimationID"] = nil,
            ["VMShotgunPumpinAnimationSpeed"] = 100
        }
    },
    ["ShotgunReload"] = false,
    ["ShotgunClipinAnimationID"] = nil,
    ["ShotgunClipinAnimationSpeed"] = 1,
    ["ShellClipinSpeed"] = 0,
    ["PreShotgunReload"] = false,
    ["PreShotgunReloadAnimationID"] = nil,
    ["PreShotgunReloadAnimationSpeed"] = 1,
    ["PreShotgunReloadSpeed"] = 0,
    ["VMShotgunClipinAnimationID"] = nil,
    ["VMShotgunClipinAnimationSpeed"] = 1,
    ["VMPreShotgunReloadAnimationID"] = nil,
    ["VMPreShotgunReloadAnimationSpeed"] = 1,
    ["ShotgunPattern"] = false,
    ["SpreadPattern"] = {
        { 0, -0.4 },
        { -0.35, 0.2 },
        { 0.35, 0.2 },
        { 0, 1 },
        { 0.95, 0.31 },
        { 0.59, -0.81 },
        { -0.59, -0.81 },
        { -0.95, 0.31 }
    },
    ["BurstFireEnabled"] = false,
    ["BulletPerBurst"] = 3,
    ["BurstRate"] = 0,
    ["CycleHandles"] = false,
    ["SelectiveFireEnabled"] = true,
    ["FireModes"] = {
        1,
        2,
        3,
        true
    },
    ["FireRates"] = {
        0.05,
        0.05,
        0.05,
        0.05
    },
    ["BurstRates"] = {
        0,
        0,
        0,
        0
    },
    ["FireModeTexts"] = {
        "SEMI-AUTO",
        "2-ROUND-BURST",
        "3-ROUND-BURST",
        "AUTO"
    },
    ["SwitchTime"] = 0,
    ["SwitchAnimationID"] = nil,
    ["SwitchAnimationSpeed"] = 100,
    ["VMSwitchAnimationID"] = nil,
    ["VMSwitchAnimationSpeed"] = 100,
    ["ExplosiveEnabled"] = false,
    ["ExplosionSoundEnabled"] = true,
    ["ExplosionSoundIDs"] = { 4334729976, 4334730465, 4334731060 },
    ["ExplosionSoundVolume"] = 3,
    ["ExplosionSoundPitchMin"] = 1,
    ["ExplosionSoundPitchMax"] = 1.5,
    ["ExplosionRadius"] = 12,
    ["DamageBasedOnDistance"] = false,
    ["SelfDamage"] = false,
    ["SelfDamageRedution"] = 1,
    ["ReduceSelfDamageOnAirOnly"] = true,
    ["CustomExplosion"] = false,
    ["ExplosionKnockback"] = true,
    ["ExplosionKnockbackPower"] = 50,
    ["ExplosionKnockbackMultiplierOnPlayer"] = 2,
    ["ExplosionKnockbackMultiplierOnTarget"] = 2,
    ["ExplosionCraterEnabled"] = true,
    ["ExplosionCraterSize"] = 3,
    ["ExplosionCraterTexture"] = { 53875997 },
    ["ExplosionCraterVisibleTime"] = 3,
    ["ExplosionCraterFadeTime"] = 1,
    ["ExplosionCraterPartColor"] = false,
    ["ProjectileType"] = "None",
    ["BulletSpeed"] = 9000,
    ["TravelType"] = "Distance",
    ["Range"] = 5000,
    ["Lifetime"] = 10,
    ["Acceleration"] = Vector3.new(0, 0, 0),
    ["Hitscan"] = true,
    ["BulletParticle"] = false,
    ["BulletType"] = "Normal",
    ["MotionBlur"] = true,
    ["BulletSize"] = 0.4,
    ["BulletBloom"] = 0,
    ["BulletBrightness"] = 400,
    ["CanSpinPart"] = false,
    ["SpinX"] = 0,
    ["SpinY"] = 0,
    ["SpinZ"] = 0,
    ["RaycastHitbox"] = false,
    ["RaycastHitboxData"] = {
        CFrame.new(-1, 1, -1),
        CFrame.new(1, 1, -1),
        CFrame.new(-1, -1, -1),
        CFrame.new(1, -1, -1),
        CFrame.new(1, -1, 1),
        CFrame.new(-1, -1, 1),
        CFrame.new(-1, 1, 1),
        CFrame.new(1, 1, 1)
    },
    ["UpdateRayInExtra"] = false,
    ["ExtraRayUpdater"] = function(_, _) end,
    ["ChargedShotEnabled"] = false,
    ["ChargingTime"] = 0,
    ["MinigunEnabled"] = false,
    ["DelayBeforeFiring"] = 0,
    ["DelayAfterFiring"] = 0,
    ["MinigunRevUpAnimationID"] = nil,
    ["MinigunRevUpAnimationSpeed"] = 100,
    ["MinigunRevDownAnimationID"] = nil,
    ["MinigunRevDownAnimationSpeed"] = 100,
    ["VMMinigunRevUpAnimationID"] = nil,
    ["VMMinigunRevUpAnimationSpeed"] = 100,
    ["VMMinigunRevDownAnimationID"] = nil,
    ["VMMinigunRevDownAnimationSpeed"] = 100,
    ["Knockback"] = 1.5,
    ["KnockbackOnKill"] = 2,
    ["Debuff"] = false,
    ["DebuffName"] = "",
    ["DebuffChance"] = 100,
    ["PenetrationType"] = "HumanoidPenetration",
    ["PenetrationDepth"] = 0,
    ["PenetrationAmount"] = 0,
    ["PenetrationIgnoreDelay"] = (1 / 0),
    ["Hitscan"] = true,
    ["FriendlyFire"] = false,
    ["BlacklistParts"] = {
        ["Part Name Here"] = true,
        ["BlacklistedPart"] = true
    },
    ["IgnoreBlacklistedParts"] = true,
    ["CanBreakGlass"] = true,
    ["HoldAndReleaseEnabled"] = false,
    ["HoldingTime"] = 0,
    ["AnimationKeyframes"] = {},
    ["VMAnimationKeyframes"] = {}
}
return v1